import addPrefix from '../../utils/addPrefix'

export const MODULE_NAME = 'TRANSPORT'
const addTransportPrefix = addPrefix(MODULE_NAME)

export const SET_LOADING = addTransportPrefix('SET_LOADING')
export const INITIAL_REQUEST = addTransportPrefix('INITIAL_REQUEST')
export const INITIAL_SUCCESS = addTransportPrefix('INITIAL_SUCCESS')
export const FETCH_ASSIGN_REQUEST = addTransportPrefix('FETCH_ASSIGN_REQUEST')
export const FETCH_ASSIGN_SUCCESS = addTransportPrefix('FETCH_ASSIGN_SUCCESS')
export const FETCH_REFUSE_REQUEST = addTransportPrefix('FETCH_REFUSE_REQUEST')
export const FETCH_REFUSE_SUCCESS = addTransportPrefix('FETCH_REFUSE_SUCCESS')
export const FETCH_ACCEPT_REQUEST = addTransportPrefix('FETCH_ACCEPT_REQUEST')
export const FETCH_ACCEPT_SUCCESS = addTransportPrefix('FETCH_ACCEPT_SUCCESS')
export const FETCH_SUBMIT_REQUEST = addTransportPrefix('FETCH_SUBMIT_REQUEST')
export const FETCH_SUBMIT_SUCCESS = addTransportPrefix('FETCH_SUBMIT_SUCCESS')
export const TO_PUBLISH_REQUEST = addTransportPrefix('TO_PUBLISH_REQUEST')
export const TO_PUBLISH_SUCCESS = addTransportPrefix('TO_PUBLISH_SUCCESS')
export const TO_ACCEPT_REQUEST = addTransportPrefix('TO_ACCEPT_REQUEST')
export const TO_ACCEPT_SUCCESS = addTransportPrefix('TO_ACCEPT_SUCCESS')
export const TO_REFUSE_REQUEST = addTransportPrefix('TO_REFUSE_REQUEST')
export const TO_REFUSE_SUCCESS = addTransportPrefix('TO_REFUSE_SUCCESS')
export const TO_SUBMIT_REQUEST = addTransportPrefix('TO_SUBMIT_REQUEST')
export const TO_SUBMIT_SUCCESS = addTransportPrefix('TO_SUBMIT_SUCCESS')
export const TO_ASSIGN_REQUEST = addTransportPrefix('TO_ASSIGN_REQUEST')
export const TO_ASSIGN_SUCCESS = addTransportPrefix('TO_ASSIGN_SUCCESS')
export const PUBLISH_REQUEST = addTransportPrefix('PUBLISH_REQUEST')
export const PUBLISH_SUCCESS = addTransportPrefix('PUBLISH_SUCCESS')
export const DENY_REQUEST = addTransportPrefix('DENY_REQUEST')
export const DENY_SUCCESS = addTransportPrefix('DENY_SUCCESS')
export const PASS_REQUEST = addTransportPrefix('PASS_REQUEST')
export const PASS_SUCCESS = addTransportPrefix('PASS_SUCCESS')
export const BACK_REQUEST = addTransportPrefix('BACK_REQUEST')
export const BACK_SUCCESS = addTransportPrefix('BACK_SUCCESS')
